version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/booklist-react
    environment:
      - VIRTUAL_HOST=booklist-react.exzork.me
      - LETSENCRYPT_HOST=booklist-react.exzork.me
      - LETSENCRYPT_EMAIL=muhammadeko.if@gmail.com
networks:
  default :
    name: nginx-proxy